name: Build

on:
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Test and Analyze
    runs-on: ubuntu-latest
    environment: CodeSec
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: 'maven'

      - name: Build and Test
        run: ./mvnw --batch-mode verify

      - name: Contrast Scan Analyze
        uses: Contrast-Security-OSS/contrastscan-action@v2.0.2
        with:
          artifact: ./target/spring-petclinic-2.5.0-SNAPSHOT.jar
          apiUrl: ${{ secrets.CONTRAST__API__URL }}
          apiKey: ${{ secrets.CONTRAST__API__API_KEY }}
          orgId: ${{ secrets.CONTRAST__API__ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST__API__AUTH_HEADER }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
